spring.application.name=minimaxi-backend

server.port=${PORT:8080}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/minimaxi_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:post123}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false
groq.api.key=${GROQ_API_KEY}

MAIL_FROM=noreply.minimaxi@gmail.com

APP_FRONTEND_URL=${APP_FRONTEND_URL:https://minimaxi.vercel.app}

scheduler.prediction.enabled=${SCHEDULER_PREDICTION_ENABLED:false}
scheduler.estimated-hours.enabled=${SCHEDULER_ESTIMATED_HOURS_ENABLED:true}
scheduler.due-date.enabled=${SCHEDULER_DUE_DATE_ENABLED:true}
